# Changes here will be overwritten by Copier
_commit: 3c5800e
_src_path: https://github.com/oarepo/nrp-app-copier
languages: cs
repository_description: 'National Metadata Directory

    '
repository_human_name: NMA
