# Changes here will be overwritten by Copier
_commit: 8b0d6b1
_src_path: gh:oarepo/nrp-app-copier
languages: cs
repository_description: Repository for aggregating metadata of datasets in the Czech
    Republic
repository_human_name: National Metadata Directory
