#!/bin/bash

set -e

base_directory="$(dirname "$0")"
export base_directory="$(readlink -f "$base_directory")"

export nrp_directory="$base_directory/.nrp"
export venv_directory="$base_directory/.venv"
export devtools_cli_directory="$nrp_directory/devtools"

echo "base_directory: $base_directory"

NRP_VERSION=12

# This script runs the NRP repository tools

# Environment variables
# PYTHON:
#              python executable to use for running the NRP tools
# LOCAL_NRP_DEVTOOLS_LOCATION:
#              location of the local NRP repository.
#              If set, do not clone the NRP repository but use the local one.


# If there is a local environment file, source it. This is necessary on Mac OS X
# to set the correct environment variables for the python executable.
# An example file on mac os x is:
#
# ❯ cat ~/.envrc.local
#
# # dynamic libraries (such as cairo)
# export DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib
#
if [ -f ~/.envrc.local ] ; then
  source ~/.envrc.local
fi

PYTHON_VERSION="${PYTHON_VERSION:-3.12}"
SUPPORTED_PYTHON_PATHS=(
  "/usr/bin/python${PYTHON_VERSION}"
  "/opt/homebrew/bin/python${PYTHON_VERSION}"
  "/usr/local/bin/python${PYTHON_VERSION}"
)

if [ -z "$PYTHON" ] ; then

  # find a supported python
  for python_path in "${SUPPORTED_PYTHON_PATHS[@]}"; do
      if [ -x "$python_path" ] ; then
        # try to execute it
        if command -v $python_path >/dev/null 2>&1; then
            PYTHON=$python_path
            break
        fi
      fi
  done

  if [ -z "$PYTHON" ] ; then
    echo "No supported python found. Please install python 3.10
    or set the PYTHON environment variable to the python executable."
    exit 1
  fi
fi

echo "Will use python at path $PYTHON"
export PYTHON

check_create_nrp_venv() {

  if [ ! -d "$venv_directory" ] ; then
    mkdir "$venv_directory"
  fi

  # if there is a devtools directory and can not call nrp-devtools inside it,
  # remove the directory
  if [ -d "$devtools_cli_directory" ] ; then
    if ! "$devtools_cli_directory"/bin/nrp-devtools --help >/dev/null 2>&1 ; then
      rm -rf "$devtools_cli_directory"
    fi
  fi

  if [ ! -d "$devtools_cli_directory" ] ; then
    # make parent directory if it does not exist
    if [ ! -d "$(dirname "$devtools_cli_directory")" ] ; then
      mkdir -p "$(dirname "$devtools_cli_directory")"
    fi
    $PYTHON -m venv "${devtools_cli_directory}"
    "${devtools_cli_directory}"/bin/pip install -U setuptools pip wheel
    if [ -z "$LOCAL_NRP_DEVTOOLS_LOCATION" ] ; then
      "${devtools_cli_directory}"/bin/pip install "nrp-devtools==${NRP_VERSION}.*"
    else
      "${devtools_cli_directory}"/bin/pip install -e "$LOCAL_NRP_DEVTOOLS_LOCATION"
    fi
  fi
}


# main entrypoint in here

check_create_nrp_venv
source "$devtools_cli_directory"/bin/activate
"$devtools_cli_directory"/bin/nrp-devtools "$@"
