from test_datacite.resources.records.config import TestDataciteResourceConfig
from test_datacite.resources.records.resource import TestDataciteResource
from test_datacite.services.records.config import TestDataciteServiceConfig
from test_datacite.services.records.service import TestDataciteService

TEST_DATACITE_RECORD_RESOURCE_CONFIG = TestDataciteResourceConfig


TEST_DATACITE_RECORD_RESOURCE_CLASS = TestDataciteResource


TEST_DATACITE_RECORD_SERVICE_CONFIG = TestDataciteServiceConfig


TEST_DATACITE_RECORD_SERVICE_CLASS = TestDataciteService
