version: "3.5"
name: "nma"
services:
  cache:
    image: redis:7
    restart: "unless-stopped"
    read_only: true
    ports:
      - "${INVENIO_REDIS_HOST}:${INVENIO_REDIS_PORT}:6379"
  db:
    image: postgres:15-alpine
    restart: "unless-stopped"
    environment:
      - "POSTGRES_USER=${INVENIO_DATABASE_USER}"
      - "POSTGRES_PASSWORD=${INVENIO_DATABASE_PASSWORD}"
      - "POSTGRES_DB=${INVENIO_DATABASE_DBNAME}"
    ports:
      - "${INVENIO_DATABASE_HOST}:${INVENIO_DATABASE_PORT}:5432"
  mq:
    image: rabbitmq:3-management
    restart: "unless-stopped"
    environment:
      RABBITMQ_DEFAULT_USER: "${INVENIO_RABBIT_USER}"
      RABBITMQ_DEFAULT_PASS: "${INVENIO_RABBIT_PASSWORD}"
    ports:
      - "${INVENIO_RABBIT_HOST}:${INVENIO_RABBIT_ADMIN_PORT}:15672"
      - "${INVENIO_RABBIT_HOST}:${INVENIO_RABBIT_PORT}:5672"

  search:
    image: bitnami/opensearch:2
    restart: "unless-stopped"
    environment:
      # settings only for development. DO NOT use in production!
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
      - OPENSEARCH_PLUGINS=analysis-icu
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    ports:
      - "${INVENIO_OPENSEARCH_HOST}:${INVENIO_OPENSEARCH_PORT}:9200"
      - "${INVENIO_OPENSEARCH_HOST}:${INVENIO_OPENSEARCH_CLUSTER_PORT}:9600"
  s3:
    image: minio/minio:latest
    restart: "unless-stopped"
    environment:
      MINIO_ROOT_USER: ${INVENIO_S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${INVENIO_S3_SECRET_KEY}
    command: server /data --console-address :9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "${INVENIO_S3_HOST}:${INVENIO_S3_PORT}:9000"
      - "${INVENIO_S3_HOST}:${INVENIO_S3_PORT1}:9001"
