# Changes here will be overwritten by Copier
_commit: 47fe7e1
_src_path: https://github.com/oarepo/nrp-model-copier
base_model: rdm_basic
model_description: Structured collections of research data, identified with a persistent
    identifier
model_human_name: Datasets
